In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/Users/jang-wonjun/Desktop/DMISLab/ToxAgent/molecular_feature/pairs_fg_stereo_merged_nodot.csv")

In [5]:
delta_columns = ['dataset_name', 'endpoint', 'toxic_smiles', 'nontoxic_smiles', 'tanimoto_sim',
       'delta_MW', 'delta_logP', 'delta_TPSA', 'delta_HBD', 'delta_HBA',
       'delta_RotB', 'delta_RingCount', 'delta_AromRingCount']

In [6]:
df_delta = df[delta_columns]

In [4]:
print(df.columns)
df.head(2)

Index(['dataset_name', 'endpoint', 'toxic_smiles', 'nontoxic_smiles',
       'toxic_scaffold_smiles', 'nontoxic_scaffold_smiles', 'tanimoto_sim',
       'delta_MW', 'delta_logP', 'delta_TPSA', 'delta_HBD', 'delta_HBA',
       'delta_RotB', 'delta_RingCount', 'delta_AromRingCount',
       'toxic_canonical_smiles', 'nontoxic_canonical_smiles', 'toxic_fg_names',
       'toxic_fg_counts', 'toxic_total_fg_count', 'toxic_fg_full',
       'nontoxic_fg_names', 'nontoxic_fg_counts', 'nontoxic_total_fg_count',
       'nontoxic_fg_full', 'has_fg_diff', 'unique_fg', 'toxic_chiral_centers',
       'toxic_ez_bonds', 'toxic_has_chirality', 'toxic_has_ez_bonds',
       'nontoxic_chiral_centers', 'nontoxic_ez_bonds',
       'nontoxic_has_chirality', 'nontoxic_has_ez_bonds', 'chiral_diff_loose',
       'ez_diff_loose', 'stereo_diff_type_loose', 'n_fg_diff', 'n_stereo_diff',
       'n_diff_features', 'diff_type', 'step_num'],
      dtype='object')

,dataset_name,endpoint,toxic_smiles,nontoxic_smiles,toxic_scaffold_smiles,nontoxic_scaffold_smiles,tanimoto_sim,delta_MW,delta_logP,delta_TPSA,...,nontoxic_has_chirality,nontoxic_has_ez_bonds,chiral_diff_loose,ez_diff_loose,stereo_diff_type_loose,n_fg_diff,n_stereo_diff,n_diff_features,diff_type,step_num
0,sider_train,Blood and lymphatic system disorders,COCCc1ccc(OCC(O)CNC(C)C)cc1,COC(=O)CCc1ccc(OCC(O)CNC(C)C)cc1,c1ccccc1,c1ccccc1,0.704545,27.994915,0.0833,17.07,...,NaN,NaN,NaN,NaN,NaN,5,0,5,only_fg,multi_step
1,sider_train,Blood and lymphatic system disorders,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O...,CC1CC2C3CCC4=CC(=O)C=CC4(C)[C@@]3(F)C(O)CC2(C)...,O=C1C=CC2C(=C1)CCC1C3CCCC3CCC21,O=C1C=CC2C(=C1)CCC1C3CCCC3CCC21,0.847458,17.966113,1.2465,20.23,...,True,False,True,False,chiral_only,2,2,4,both,multi_step

In [7]:
df_delta.head(2)

,dataset_name,endpoint,toxic_smiles,nontoxic_smiles,tanimoto_sim,delta_MW,delta_logP,delta_TPSA,delta_HBD,delta_HBA,delta_RotB,delta_RingCount,delta_AromRingCount
0,sider_train,Blood and lymphatic system disorders,COCCc1ccc(OCC(O)CNC(C)C)cc1,COC(=O)CCc1ccc(OCC(O)CNC(C)C)cc1,0.704545,27.994915,0.0833,17.07,0.0,1.0,0.0,0.0,0.0
1,sider_train,Blood and lymphatic system disorders,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O...,CC1CC2C3CCC4=CC(=O)C=CC4(C)[C@@]3(F)C(O)CC2(C)...,0.847458,17.966113,1.2465,20.23,1.0,1.0,0.0,0.0,0.0

In [8]:
df_delta[['delta_MW', 'delta_logP', 'delta_TPSA', 'delta_HBD', 'delta_HBA',
       'delta_RotB', 'delta_RingCount', 'delta_AromRingCount']].describe()

,delta_MW,delta_logP,delta_TPSA,delta_HBD,delta_HBA,delta_RotB,delta_RingCount,delta_AromRingCount
count,16193.000000,16193.000000,16193.000000,16193.000000,16193.000000,16193.000000,16193.0,16193.0
mean,22.390939,0.430269,6.095050,0.127092,0.394059,0.633669,0.0,0.0
std,18.542952,0.395350,9.010006,0.347425,0.561030,0.862199,0.0,0.0
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
25%,12.019986,0.139100,0.000000,0.000000,0.000000,0.000000,0.0,0.0
50%,15.994915,0.344980,0.000000,0.000000,0.000000,0.000000,0.0,0.0
75%,30.010565,0.644800,9.230000,0.000000,1.000000,1.000000,0.0,0.0
max,212.177630,5.071300,66.760000,2.000000,3.000000,13.000000,0.0,0.0