In [2]:
import pandas as pd

In [3]:
safe_pair = pd.read_csv("/Users/jang-wonjun/Desktop/DMISLab/ToxAgent/molecule_safe_ver/pairs_safe_compared.csv")

In [4]:
print(len(safe_pair))
safe_pair.head(2)

16193

,dataset_name,endpoint,toxic_smiles,nontoxic_smiles,toxic_safe,nontoxic_safe,toxic_safe_fragments,nontoxic_safe_fragments,common_safe_fragments,only_toxic_safe_fragments,only_nontoxic_safe_fragments,n_common_safe,n_only_toxic_safe,n_only_nontoxic_safe,has_safe_diff,unique_safe
0,sider_train,Blood and lymphatic system disorders,COCCc1ccc(OCC(O)CNC(C)C)cc1,COC(=O)CCc1ccc(OCC(O)CNC(C)C)cc1,c17ccc4cc1.C3C(O)C5.C2C7.C6(C)C.CO2.O34.N56,c17ccc4cc1.C2(=O)CC7.C3C(O)C5.C6(C)C.CO2.O34.N56,C2C7.C3C(O)C5.C6(C)C.CO2.N56.O34.c17ccc4cc1,C2(=O)CC7.C3C(O)C5.C6(C)C.CO2.N56.O34.c17ccc4cc1,C3C(O)C5.C6(C)C.CO2.N56.O34.c17ccc4cc1,C2C7,C2(=O)CC7,6,1,1,True,"[{""fragment"": ""C2C7"", ""reason"": ""only_in_toxic..."
1,sider_train,Blood and lymphatic system disorders,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O...,CC1CC2C3CCC4=CC(=O)C=CC4(C)[C@@]3(F)C(O)CC2(C)...,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C15O...,CC1CC2C3CCC4=CC(=O)C=CC4(C)[C@@]3(F)C(O)CC2(C)...,C5(=O)CO.CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)C...,C5(=O)CCl.CC1CC2C3CCC4=CC(=O)C=CC4(C)[C@@]3(F)...,NaN,C5(=O)CO.CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)C...,C5(=O)CCl.CC1CC2C3CCC4=CC(=O)C=CC4(C)[C@@]3(F)...,0,2,2,True,"[{""fragment"": ""C5(=O)CO"", ""reason"": ""only_in_t..."

In [5]:
commom_frage_pairs = safe_pair[safe_pair['n_common_safe'].ne(0)]
print(len(commom_frage_pairs))
commom_frage_pairs.head(2)

9916

,dataset_name,endpoint,toxic_smiles,nontoxic_smiles,toxic_safe,nontoxic_safe,toxic_safe_fragments,nontoxic_safe_fragments,common_safe_fragments,only_toxic_safe_fragments,only_nontoxic_safe_fragments,n_common_safe,n_only_toxic_safe,n_only_nontoxic_safe,has_safe_diff,unique_safe
0,sider_train,Blood and lymphatic system disorders,COCCc1ccc(OCC(O)CNC(C)C)cc1,COC(=O)CCc1ccc(OCC(O)CNC(C)C)cc1,c17ccc4cc1.C3C(O)C5.C2C7.C6(C)C.CO2.O34.N56,c17ccc4cc1.C2(=O)CC7.C3C(O)C5.C6(C)C.CO2.O34.N56,C2C7.C3C(O)C5.C6(C)C.CO2.N56.O34.c17ccc4cc1,C2(=O)CC7.C3C(O)C5.C6(C)C.CO2.N56.O34.c17ccc4cc1,C3C(O)C5.C6(C)C.CO2.N56.O34.c17ccc4cc1,C2C7,C2(=O)CC7,6,1,1,True,"[{""fragment"": ""C2C7"", ""reason"": ""only_in_toxic..."
3,sider_train,Blood and lymphatic system disorders,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O...,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(Cl)C(O)CC2(C)C1(...,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C15O...,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(Cl)C(O)CC2(C)C15...,C5(=O)CO.CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)C...,C5(=O)CO.CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(Cl)C(O)...,C5(=O)CO,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C15O,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(Cl)C(O)CC2(C)C15O,1,1,1,True,"[{""fragment"": ""CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F..."

In [6]:
commom_frage_pairs['n_only_nontoxic_safe'].value_counts()

n_only_nontoxic_safe
1     5417
2     1132
3      703
4      693
5      621
6      494
7      455
8      198
9      108
0       28
10      22
11      17
17      13
22       3
20       3
14       3
12       3
13       2
18       1
Name: count, dtype: int64

In [7]:
commom_frage_pairs = commom_frage_pairs[
    ~((commom_frage_pairs['n_only_nontoxic_safe'] == 0) & (commom_frage_pairs['n_only_toxic_safe'] == 0))
]

print(len(commom_frage_pairs))
commom_frage_pairs.head(2)

9891

,dataset_name,endpoint,toxic_smiles,nontoxic_smiles,toxic_safe,nontoxic_safe,toxic_safe_fragments,nontoxic_safe_fragments,common_safe_fragments,only_toxic_safe_fragments,only_nontoxic_safe_fragments,n_common_safe,n_only_toxic_safe,n_only_nontoxic_safe,has_safe_diff,unique_safe
0,sider_train,Blood and lymphatic system disorders,COCCc1ccc(OCC(O)CNC(C)C)cc1,COC(=O)CCc1ccc(OCC(O)CNC(C)C)cc1,c17ccc4cc1.C3C(O)C5.C2C7.C6(C)C.CO2.O34.N56,c17ccc4cc1.C2(=O)CC7.C3C(O)C5.C6(C)C.CO2.O34.N56,C2C7.C3C(O)C5.C6(C)C.CO2.N56.O34.c17ccc4cc1,C2(=O)CC7.C3C(O)C5.C6(C)C.CO2.N56.O34.c17ccc4cc1,C3C(O)C5.C6(C)C.CO2.N56.O34.c17ccc4cc1,C2C7,C2(=O)CC7,6,1,1,True,"[{""fragment"": ""C2C7"", ""reason"": ""only_in_toxic..."
3,sider_train,Blood and lymphatic system disorders,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O...,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(Cl)C(O)CC2(C)C1(...,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C15O...,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(Cl)C(O)CC2(C)C15...,C5(=O)CO.CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)C...,C5(=O)CO.CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(Cl)C(O)...,C5(=O)CO,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C15O,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(Cl)C(O)CC2(C)C15O,1,1,1,True,"[{""fragment"": ""CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F..."

In [8]:
commom_frage_pairs.to_csv("/Users/jang-wonjun/Desktop/DMISLab/ToxAgent/molecule_safe_ver/commom_frage_pairs.csv", index=False)

In [9]:
safe_with_smiles = pd.read_csv("/Users/jang-wonjun/Desktop/DMISLab/ToxAgent/molecule_safe_ver/commom_frage_pairs_with_smiles.csv")

In [10]:
print(safe_with_smiles.columns)
safe_with_smiles.head(2)

Index(['dataset_name', 'endpoint', 'toxic_smiles', 'nontoxic_smiles',
       'toxic_safe', 'nontoxic_safe', 'toxic_safe_fragments',
       'nontoxic_safe_fragments', 'common_safe_fragments',
       'only_toxic_safe_fragments', 'only_nontoxic_safe_fragments',
       'n_common_safe', 'n_only_toxic_safe', 'n_only_nontoxic_safe',
       'toxic_safe_decoded_smiles', 'nontoxic_safe_decoded_smiles',
       'toxic_safe_fragments_smiles', 'nontoxic_safe_fragments_smiles',
       'only_toxic_safe_fragments_smiles',
       'only_nontoxic_safe_fragments_smiles'],
      dtype='object')

,dataset_name,endpoint,toxic_smiles,nontoxic_smiles,toxic_safe,nontoxic_safe,toxic_safe_fragments,nontoxic_safe_fragments,common_safe_fragments,only_toxic_safe_fragments,only_nontoxic_safe_fragments,n_common_safe,n_only_toxic_safe,n_only_nontoxic_safe,toxic_safe_decoded_smiles,nontoxic_safe_decoded_smiles,toxic_safe_fragments_smiles,nontoxic_safe_fragments_smiles,only_toxic_safe_fragments_smiles,only_nontoxic_safe_fragments_smiles
0,sider_train,Blood and lymphatic system disorders,COCCc1ccc(OCC(O)CNC(C)C)cc1,COC(=O)CCc1ccc(OCC(O)CNC(C)C)cc1,c17ccc4cc1.C3C(O)C5.C2C7.C6(C)C.CO2.O34.N56,c17ccc4cc1.C2(=O)CC7.C3C(O)C5.C6(C)C.CO2.O34.N56,C2C7.C3C(O)C5.C6(C)C.CO2.N56.O34.c17ccc4cc1,C2(=O)CC7.C3C(O)C5.C6(C)C.CO2.N56.O34.c17ccc4cc1,C3C(O)C5.C6(C)C.CO2.N56.O34.c17ccc4cc1,C2C7,C2(=O)CC7,6,1,1,c1(CCOC)ccc(OCC(O)CNC(C)C)cc1,c1(CCC(=O)OC)ccc(OCC(O)CNC(C)C)cc1,[CH2]([CH2][*:7])[*:2].[CH2]([CH]([OH])[CH2][*...,[C](=[O])([CH2][CH2][*:7])[*:2].[CH2]([CH]([OH...,[CH2]([CH2][*:7])[*:2],[C](=[O])([CH2][CH2][*:7])[*:2]
1,sider_train,Blood and lymphatic system disorders,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O...,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(Cl)C(O)CC2(C)C1(...,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C15O...,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(Cl)C(O)CC2(C)C15...,C5(=O)CO.CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)C...,C5(=O)CO.CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(Cl)C(O)...,C5(=O)CO,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C15O,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(Cl)C(O)CC2(C)C15O,1,1,1,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(F)C(O)CC2(C)C1(O...,CC1CC2C3CCC4=CC(=O)C=CC4(C)C3(Cl)C(O)CC2(C)C1(...,[C](=[O])([CH2][OH])[*:5].[CH3][CH]1[CH2][CH]2...,[C](=[O])([CH2][OH])[*:5].[CH3][CH]1[CH2][CH]2...,[CH3][CH]1[CH2][CH]2[CH]3[CH2][CH2][C]4=[CH][C...,[CH3][CH]1[CH2][CH]2[CH]3[CH2][CH2][C]4=[CH][C...

In [14]:
for column in safe_with_smiles.columns:
    print(column,":")
    print(safe_with_smiles[column].iloc[4])

dataset_name :
sider_train
endpoint :
Blood and lymphatic system disorders
toxic_smiles :
CCCC1OC2CC3C4CCC5=CC(=O)C=CC5(C)C4C(O)CC3(C)C2(C(=O)CO)O1
nontoxic_smiles :
CC1(C)O[C@@H]2C[C@H]3C4CCC5=CC(=O)C=CC5(C)[C@H]4C(O)CC3(C)[C@]2(C(=O)CO)O1
toxic_safe :
C17OC2CC3C4CCC5=CC(=O)C=CC5(C)C4C(O)CC3(C)C26O1.C6(=O)CO.CCC7
nontoxic_safe :
CC1(C)O[C@@H]2C[C@H]3C4CCC5=CC(=O)C=CC5(C)[C@H]4C(O)CC3(C)[C@]26O1.C6(=O)CO
toxic_safe_fragments :
C17OC2CC3C4CCC5=CC(=O)C=CC5(C)C4C(O)CC3(C)C26O1.C6(=O)CO.CCC7
nontoxic_safe_fragments :
C6(=O)CO.CC1(C)O[C@@H]2C[C@H]3C4CCC5=CC(=O)C=CC5(C)[C@H]4C(O)CC3(C)[C@]26O1
common_safe_fragments :
C6(=O)CO
only_toxic_safe_fragments :
C17OC2CC3C4CCC5=CC(=O)C=CC5(C)C4C(O)CC3(C)C26O1.CCC7
only_nontoxic_safe_fragments :
CC1(C)O[C@@H]2C[C@H]3C4CCC5=CC(=O)C=CC5(C)[C@H]4C(O)CC3(C)[C@]26O1
n_common_safe :
1
n_only_toxic_safe :
2
n_only_nontoxic_safe :
1
toxic_safe_decoded_smiles :
C1(CCC)OC2CC3C4CCC5=CC(=O)C=CC5(C)C4C(O)CC3(C)C2(C(=O)CO)O1
nontoxic_safe_decoded_smiles :
CC1(C)O[C@@H]2C[C@H]3C4CCC5=CC(=O)C=CC5(C)[C@H]4C(O)CC3(C)[C@]2(C(=O)CO)O1
toxic_safe_fragments_smiles :
[CH]1([*:7])[O][CH]2[CH2][CH]3[CH]4[CH2][CH2][C]5=[CH][C](=[O])[CH]=[CH][C]5([CH3])[CH]4[CH]([OH])[CH2][C]3([CH3])[C]2([*:6])[O]1.[C](=[O])([CH2][OH])[*:6].[CH3][CH2][CH2][*:7]
nontoxic_safe_fragments_smiles :
[C](=[O])([CH2][OH])[*:6].[CH3][C]1([CH3])[O][C@@H]2[CH2][C@H]3[CH]4[CH2][CH2][C]5=[CH][C](=[O])[CH]=[CH][C]5([CH3])[C@H]4[CH]([OH])[CH2][C]3([CH3])[C@]2([*:6])[O]1
only_toxic_safe_fragments_smiles :
[CH]1([*:7])[O][CH]2[CH2][CH]3[CH]4[CH2][CH2][C]5=[CH][C](=[O])[CH]=[CH][C]5([CH3])[CH]4[CH]([OH])[CH2][C]3([CH3])[C]2([*:6])[O]1.[CH3][CH2][CH2][*:7]
only_nontoxic_safe_fragments_smiles :
[CH3][C]1([CH3])[O][C@@H]2[CH2][C@H]3[CH]4[CH2][CH2][C]5=[CH][C](=[O])[CH]=[CH][C]5([CH3])[C@H]4[CH]([OH])[CH2][C]3([CH3])[C@]2([*:6])[O]1